### ISSUE TITLE
device discover problem

### ISSUE THREAD

**Issue by Marcin54864** [Guitar-Man/ync-tools#1]
I have CD-N301 (1.09) (IP 192.168.1.80)

ping work:

PING 192.168.1.80 (192.168.1.80) 56(84) bytes of data.
64 bytes from 192.168.1.80: icmp_seq=1 ttl=128 time=5.11 ms

but device discover does not work:

YNC Console 0.24.1 (API 0.41.2)
> device discover
Searching devices...
No device found.

Please help.

**Comment by alexandrecourtois** [comment]
Without additional information about your network configuration, I can't help you.
